[package]
name = "monte_carlo_polygon"
version = "0.1.0"
edition = "2021"

[dependencies]
fastrand = "1.9.0"
geo = "0.27.0"
rayon = "1.8.0"
rust_xlsxwriter = "0.43.0"
wgpu = "25.0.0"
pollster = "0.3.0"
bytemuck = { version = "1.14.0", features = ["derive"] }
futures-intrusive = "0.5.0"